before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
project_name: unifi-ha-presence-mqtt
builds:
  - main: ./cmd/unifi-ha-presence-mqtt
    id: "unifi-ha-presence-mqtt"
    binary: unifi-ha-presence-mqtt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
dockers:
  - image_templates:
      - "gsdevme/unifi-ha-presence-mqtt:latest"
      - "gsdevme/unifi-ha-presence-mqtt:{{ .Tag }}"
      - "gsdevme/unifi-ha-presence-mqtt:v{{ .Major }}"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'