before:
  hooks:
    - go mod tidy
    - go generate ./...
    - go test ./...
project_name: unifi-ha-presence-mqtt
builds:
  - main: ./cmd/unifi-ha-presence-mqtt
    id: "unifi-ha-presence-mqtt"
    binary: unifi-ha-presence-mqtt
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
#dockers:
#  # You can have multiple Docker images.
#  -
#    goos: linux
#    goarch: amd64
#
##    image_templates:
##      - "myuser/myimage:latest"
##      - "myuser/myimage:{{ .Tag }}"
##      - "myuser/myimage:{{ .Tag }}-{{ .Env.GO_VERSION }}"
##      - "myuser/myimage:v{{ .Major }}"
##      - "gcr.io/myuser/myimage:latest"
#
#    skip_push: true
#    dockerfile: Dockerfile
#    use: docker
#
#    build_flag_templates:
#      - "--label=org.opencontainers.image.created={{.Date}}"
#      - "--label=org.opencontainers.image.title={{.ProjectName}}"
#      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
#      - "--label=org.opencontainers.image.version={{.Version}}"
#      - "--platform=linux/arm64"
archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'