name: build
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v2
        with:
          go-version: '^1.17'
      - name: build
        uses: goreleaser/goreleaser-action@v2
        with:
          version: latest
          args: build --snapshot --rm-dist
      - name: Create Git Semver Tag
        if: github.ref == 'refs/heads/master'
        run: npx semantic-release --branches master -p @semantic-release/commit-analyzer -p @semantic-release/release-notes-generator -p @semantic-release/github
